"""empty message

Revision ID: d2c623227b64
Revises: facffb0b021e
Create Date: 2018-12-23 00:36:04.129354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c623227b64'
down_revision = 'facffb0b021e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AorB', sa.String(), nullable=True),
    sa.Column('ticketNo', sa.String(), nullable=True),
    sa.Column('heatNo', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('productHeight', sa.String(), nullable=True),
    sa.Column('ringHeight', sa.String(), nullable=True),
    sa.Column('jobNo', sa.String(), nullable=True),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Record')
    # ### end Alembic commands ###
